services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: liquidity_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
